### ISSUE TITLE
Bandits are not syncing between players in Skyrim.

### ISSUE THREAD

**Issue by F1r3w477** [SkyrimTogether/issues-game#137]
## Description

When you are in Skyrim (the main open world part of the game) Bandits locations and deaths do not sync between players.

Note: Locations of Bandits in caves and places that you load into, work just fine (aside from the bug report I made previously) and at the time this happened, wolves, and other creatures were syncing just fine. 

EDIT: Just went into a cave and the bandits were not syncing in a cave either

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
2.5 (may or may not be related to reproduction) - Go into some houses and leave them.
3. Find bandits and fight them

## Reproduction rate

Happened twice, but we only fought bandits in Skyrim twice.

## Expected result

Syncing locations and deaths (of Bandits) between players.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Boosik** [comment]
This happens to me as well and not just for bandits or vampiric acolytes but for basically any enemy. It does not happen everytime. This issue starts randomly occuring for me and my GF and it is extremely annoying as we often fight enemies that the other player cannot see.

**Comment by ButtonSmasher** [comment]
This is just a desync. It's early stage so i wouldn't be to bothered it by now. Sometimes re-entering a cell fixes it. Sometimes i even had dead bodies drop from thin air because that was the enemy my other players saw. Which is hillirious in some way.

**Comment by Pokang** [comment]
This is most likely fixed now, as we pushed a fix that should fix the desync issue, I'd love if you could confirm me that this is not happening anymore.

**Comment by F1r3w477** [comment]
@Pokang I am getting on right now, ill let you know if I experience the issue again <3

**Comment by ButtonSmasher** [comment]
Isn't that because bandits are spawned in? Like if you're with 3 people the bandits will spawn in 3 times more. Maybe that has something to do with it.. Haven't seen Animals spawn extra in so that could be a thing.

**Comment by ButtonSmasher** [comment]
@F1r3w477 I had that too, but they instantly die or are naked and die after a few seconds. I think it's just a weird cell reload?

I fixed this by going in and out of that cell or just reloading saves before i died :)

**Comment by f13rce** [comment]
This should be fixed with the latest version of the mod. Please open the issue again if it persists. :)

**Comment by ShowMeTheNugget** [comment]
My friend and I are still having issues with enemies, animals, etc. not syncing with each other. We are seeing completely different enemies. This is after the newest update and we are both on the same version.

**Comment by Alexpop11** [comment]
Currently I see the same npcs as my friend, but they are not synced. It is like they are duplicated.

**Comment by f13rce** [comment]
The patch isn't live yet, which explains why you're still experiencing this.

**Comment by Alexpop11** [comment]
> The patch isn't live yet, which explains why you're still experiencing this.

Is there an ETA on the patch? Just wondering if it will be out anytime soon

**Comment by ShowMeTheNugget** [comment]
Oh, that makes sense! Thank you for letting me know, f13rce! I appreciate all that you guys do!
