### ISSUE TITLE
When i'm trying to connect to the server, my game crashes

### ISSUE THREAD

**Issue by loochek** [SkyrimTogether/issues-game#275]
## Description

When i'm trying to connect to the server, my game crashes

There is a string from server log:
{"date":"2019-05-18 18:13:01,690", "level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null" }

This problem appears both with Docker container on VPS and local Windows serer

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Try to connect to the server.
3. Crash.

## Reproduction rate

I tried to connect 5 times

## Expected result

Working game

## Your environment

The Elder Scrolls V: Skyrim @ Windows 10 x64
[crashdump.zip](https://github.com/SkyrimTogether/issues-game/files/3194096/crashdump.zip)

**Comment by WopsS** [comment]
Was fixed in the current build.

**Comment by Pokang** [comment]
@loochek Can you confirm us that this is still happening on newer builds for you?

**Comment by loochek** [comment]
No, sorry, but for me this bug has been fixed after first closing

**Comment by Pokang** [comment]
Alright, thank you for your report!
Closing since it's resolved.
